#!/bin/bash

: ${PREFIX=c89-char}

export PATH=
[ "`${PREFIX}/way len`" == "0" ] || echo "FAILURE"
[ "`${PREFIX}/way count`" == "0" ] || echo "FAILURE"

[ "`${PREFIX}/way get`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -t`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --tail`" == "" ] || echo "FAILURE"

[ "`${PREFIX}/way delete`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -t`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --tail`" == "" ] || echo "FAILURE"

[ "`${PREFIX}/way insert /mine`" == "/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 0 /mine`" == "/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 0 /mine`" == "/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 1 /mine`" == "/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 1 /mine`" == "/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 2 /mine`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 2 /mine`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -t /mine`" == "/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --tail /mine`" == "/mine" ] || echo "FAILURE"

export PATH=/one
[ "`${PREFIX}/way len`" == "4" ] || echo "FAILURE"
[ "`${PREFIX}/way count`" == "1" ] || echo "FAILURE"

[ "`${PREFIX}/way get`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 0`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 0`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -t`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way get --tail`" == "/one" ] || echo "FAILURE"

[ "`${PREFIX}/way delete`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 1`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 1`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -t`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --tail`" == "" ] || echo "FAILURE"

[ "`${PREFIX}/way insert /mine`" == "/mine:/one" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 0 /mine`" == "/mine:/one" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 0 /mine`" == "/mine:/one" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 1 /mine`" == "/one:/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 1 /mine`" == "/one:/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 2 /mine`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 2 /mine`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -t /mine`" == "/one:/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --tail /mine`" == "/one:/mine" ] || echo "FAILURE"

export PATH=/one:/two
[ "`${PREFIX}/way len`" == "9" ] || echo "FAILURE"
[ "`${PREFIX}/way count`" == "2" ] || echo "FAILURE"

[ "`${PREFIX}/way get`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 0`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 0`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 1`" == "/two" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 1`" == "/two" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 2`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 2`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -t`" == "/two" ] || echo "FAILURE"
[ "`${PREFIX}/way get --tail`" == "/two" ] || echo "FAILURE"

[ "`${PREFIX}/way delete`" == "/two" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 0`" == "/two" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 0`" == "/two" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 1`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 1`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -t`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --tail`" == "/one" ] || echo "FAILURE"

[ "`${PREFIX}/way insert /mine`" == "/mine:/one:/two" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 0 /mine`" == "/mine:/one:/two" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 0 /mine`" == "/mine:/one:/two" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 1 /mine`" == "/one:/mine:/two" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 1 /mine`" == "/one:/mine:/two" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 2 /mine`" == "/one:/two:/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 2 /mine`" == "/one:/two:/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 3 /mine`" == "/one:/two" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 3 /mine`" == "/one:/two" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -t /mine`" == "/one:/two:/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --tail /mine`" == "/one:/two:/mine" ] || echo "FAILURE"

export PATH=/one:
[ "`${PREFIX}/way len`" == "5" ] || echo "FAILURE"
[ "`${PREFIX}/way count`" == "2" ] || echo "FAILURE"

[ "`${PREFIX}/way get`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 0`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 0`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 2`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 2`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -t`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --tail`" == "" ] || echo "FAILURE"

[ "`${PREFIX}/way delete`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 1`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 1`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -t`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --tail`" == "/one" ] || echo "FAILURE"

[ "`${PREFIX}/way insert /mine`" == "/mine:/one:" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 0 /mine`" == "/mine:/one:" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 0 /mine`" == "/mine:/one:" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 1 /mine`" == "/one:/mine:" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 1 /mine`" == "/one:/mine:" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 2 /mine`" == "/one::/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 2 /mine`" == "/one::/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 3 /mine`" == "/one:" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 3 /mine`" == "/one:" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -t /mine`" == "/one::/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --tail /mine`" == "/one::/mine" ] || echo "FAILURE"

export PATH=:/one
[ "`${PREFIX}/way len`" == "5" ] || echo "FAILURE"
[ "`${PREFIX}/way count`" == "2" ] || echo "FAILURE"

[ "`${PREFIX}/way get`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 1`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 1`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 2`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 2`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -t`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way get --tail`" == "/one" ] || echo "FAILURE"

[ "`${PREFIX}/way delete`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 0`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 0`" == "/one" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -t`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --tail`" == "" ] || echo "FAILURE"

[ "`${PREFIX}/way insert /mine`" == "/mine::/one" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 0 /mine`" == "/mine::/one" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 0 /mine`" == "/mine::/one" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 1 /mine`" == ":/mine:/one" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 1 /mine`" == ":/mine:/one" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 2 /mine`" == ":/one:/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 2 /mine`" == ":/one:/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 3 /mine`" == ":/one" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 3 /mine`" == ":/one" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -t /mine`" == ":/one:/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --tail /mine`" == ":/one:/mine" ] || echo "FAILURE"

export PATH=:
[ "`${PREFIX}/way len`" == "1" ] || echo "FAILURE"
[ "`${PREFIX}/way count`" == "2" ] || echo "FAILURE"

[ "`${PREFIX}/way get`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 2`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 2`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -t`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --tail`" == "" ] || echo "FAILURE"

[ "`${PREFIX}/way delete`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 2`" == ":" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 2`" == ":" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -t`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --tail`" == "" ] || echo "FAILURE"

[ "`${PREFIX}/way insert /mine`" == "/mine::" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 0 /mine`" == "/mine::" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 0 /mine`" == "/mine::" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 1 /mine`" == ":/mine:" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 1 /mine`" == ":/mine:" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 2 /mine`" == "::/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 2 /mine`" == "::/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 3 /mine`" == ":" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 3 /mine`" == ":" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -t /mine`" == "::/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --tail /mine`" == "::/mine" ] || echo "FAILURE"

export PATH=::
[ "`${PREFIX}/way len`" == "2" ] || echo "FAILURE"
[ "`${PREFIX}/way count`" == "3" ] || echo "FAILURE"

[ "`${PREFIX}/way get`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 0`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 1`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 2`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 2`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -i 3`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --index 3`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get -t`" == "" ] || echo "FAILURE"
[ "`${PREFIX}/way get --tail`" == "" ] || echo "FAILURE"

[ "`${PREFIX}/way delete`" == ":" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 0`" == ":" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 0`" == ":" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 1`" == ":" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 1`" == ":" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 2`" == ":" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 2`" == ":" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -i 3`" == "::" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --index 3`" == "::" ] || echo "FAILURE"
[ "`${PREFIX}/way delete -t`" == ":" ] || echo "FAILURE"
[ "`${PREFIX}/way delete --tail`" == ":" ] || echo "FAILURE"

[ "`${PREFIX}/way insert /mine`" == "/mine:::" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 0 /mine`" == "/mine:::" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 0 /mine`" == "/mine:::" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 1 /mine`" == ":/mine::" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 1 /mine`" == ":/mine::" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 2 /mine`" == "::/mine:" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 2 /mine`" == "::/mine:" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 3 /mine`" == ":::/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 3 /mine`" == ":::/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -i 4 /mine`" == "::" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --index 4 /mine`" == "::" ] || echo "FAILURE"
[ "`${PREFIX}/way insert -t /mine`" == ":::/mine" ] || echo "FAILURE"
[ "`${PREFIX}/way insert --tail /mine`" == ":::/mine" ] || echo "FAILURE"