name: way build and test

on:
  push:
    branches:
      - 'main'

jobs:
  way_c89_build:
    name: Build c89
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install gcc.
        run: sudo apt-get install -y gcc
      - name: Build c89
        run: ./build.sh
        working-directory: c89
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: c89-binary
          path: ./c89/way

  way_c89_test:
    name: Test c89
    runs-on: ubuntu-latest
    needs: way_c89_build
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: c89-binary
    - name: Run it.
      run: ls -R
